#!/usr/bin/env python3.6
""" Run a specific project """

import argparse
import os.path
import os
import sys
import importlib

root = os.path.dirname(__file__)

parser = argparse.ArgumentParser(description='Process some integers.')
parser.add_argument('project', help='The project to run')
#parser.add_argument('--root', help='Root directory for the code', default=root)

args = parser.parse_args()
print (args)

# Check the project exists
proj_dir = os.path.join(root, 'projects')
assert os.path.exists(proj_dir+'/%s'%args.project), 'Project %s does not exist'%args.project

# Add the proper directories to the system path so they can be imported
sys.path.append(proj_dir)
sys.path.append(root+'/src')

# Look for the configuration
for confdir in [os.environ['HOME']+'/etc/%s'%args.project, '/etc/%s'%args.project, None]:
    if not confdir:
        raise RuntimeError( 'Could not find a configuration for project %s'% args.project )
    if os.path.exists(confdir):
        break

# Load the configuration
from admingen import config
config.set_configdir(confdir)

# Run the project
print ('Starting project', args.project)
mod = importlib.import_module(args.project)
mod.run()
